mkdir "Лабораторные\Группа\ФИО"
cd "Лабораторные\Группа\ФИО"
mkdir "batch"
cd "batch"
mkdir "Скрытая папка"
echo. > "Не скрытая папка\copyhelp.txt"
attrib +h "Скрытая папка"
xcopy /? > "Не скрытая папка\copyhelp.txt"
xcopy "Не скрытая папка\copyhelp.txt" "Скрытая папка\copied_copyhelp.txt"

